server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

eureka:
  client:
    serviceUrl:
      defaultZone: https://ecommerce-website-1-k2mq.onrender.com/eureka/
  instance:
    preferIpAddress: true
    hostname: ${RENDER_EXTERNAL_HOSTNAME}

jwt:
  secret: ${JWT_SECRET:shopnest-super-secret-key-2024-minimum-256-bits-long-enough}
